version: "3.9"

services:
  web:
    image: nginx:latest
    container_name: tienda_animales_web
    ports:
      - "8080:80"
    volumes:
      - ./web:/usr/share/nginx/html:ro

  db:
    image: mysql:8.0
    container_name: tienda_animales_db
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d