version: "3.9"

services:
  web:
    build: ./web
    image: tienda_animales_web:1.0
    container_name: tienda_animales_web
    ports:
      - "8080:80"
    networks:
      - tienda_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 5s
      timeout: 3s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "256M"


  db:
    image: mysql:8.0
    container_name: tienda_animales_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    networks:
      - tienda_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: on-failure

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: tienda_animales_phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - tienda_network
    restart: on-failure

  app:
      build: ./app
      image: tienda_animales_app:1.0
      container_name: tienda_animales_app
      ports:
        - "8082:80"
      environment:
        DB_HOST: db
        DB_NAME: ${MYSQL_DATABASE}
        DB_USER: ${MYSQL_USER}
        DB_PASSWORD: ${MYSQL_PASSWORD}
      depends_on:
        - db
      networks:
        - tienda_network
      deploy:
        resources:
          limits:
            cpus: "0.50"
            memory: "256M"
      restart: on-failure

  proxy:
    image: nginx:alpine
    container_name: tienda_animales_proxy
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
      - app
    networks:
      - tienda_network

volumes:
  mysql_data:

networks:
  tienda_network: